### ISSUE TITLE
orcaslicerの設定ファイルを作成する

### ISSUE THREAD

**Issue by MibuchiYuta** [open-rdc/Creality-K1-Slicer-Profiles#1]
タイトルの通り。初めに以下の項目を作成する。また、成功時の空間の温度と湿度と天気をメモする。

- 速め 粗め
- 速め 粗め(ツリーサポートあり)
- 通常速度 細かめ
- 通常速度 細かめ(ツリーサポートあり)

**Comment by MibuchiYuta** [comment]
orcaslicerの設定ファイルはデフォルトで用意されているものをベースに変更していく。

**Comment by MibuchiYuta** [comment]
フィラメントは kexcelled のplaを使用する

**Comment by MibuchiYuta** [comment]
@hellocit ベンチマークモデルの候補を早めに決定してください

**Comment by nkm071** [comment]
@MibuchiYuta 以前，紹介していただいたベンチマークモデルのgithubページを以下に記載しました．3D Benchyと比較して，見るべき指標が分かりやすいと考えるのでkickstarter-autodesk-3dでよいかなと考えますがいかかでしょうか．

https://github.com/kickstarter/kickstarter-autodesk-3d

**Comment by nkm071** [comment]
**方針**
デフォルトの設定を用いて印刷時間がどれほどかかるか，次に，粗め，細かめにした時の3D プリンタの挙動や造形物について観察する．

**Comment by MibuchiYuta** [comment]
> @MibuchiYuta 以前，紹介していただいたベンチマークモデルのgithubページを以下に記載しました．3D Benchyと比較して，見るべき指標が分かりやすいと考えるのでkickstarter-autodesk-3dでよいかなと考えますがいかかでしょうか．
> 
> https://github.com/kickstarter/kickstarter-autodesk-3d

大丈夫です

**Comment by MibuchiYuta** [comment]
> **方針** デフォルトの設定を用いて印刷時間がどれほどかかるか，次に，粗め，細かめにした時の3D プリンタの挙動や造形物について観察する．

@hellocit こちらお忘れなく

> 成功時の空間の温度と湿度と天気をメモする

**Comment by nkm071** [comment]
承知しました．

**Comment by nkm071** [comment]
https://docs.google.com/document/d/12Ni78JbNmHuk7BiG3rXoD1zSS72fnm0MQ8EULhiQKTo/edit?usp=sharing

メモのひな型を上記に示す．気になることがあれば記入する．

**Comment by MibuchiYuta** [comment]
@hellocit 情報を分散させないでください。issueに気軽に書き込んで大丈夫です。

**Comment by MibuchiYuta** [comment]
@hellocit #12 の問題が解決しましたので、作業を開始してください。最初の作業確認の期限ですが、4/5まででお願いします。下記の2番までを想定しています。

**Comment by MibuchiYuta** [comment]
設定ファイルの詰めかたについて検討しました。参考にしてください。

## 1 マシンスペックの確認
流量と印刷速度の最大を計測し、それを基準にする。
orcaslicerのキャリブレーションメニューから確認できます。(Max Volmetric speedとVFA。VFAはwiki情報なし [詳細](https://github.com/SoftFever/OrcaSlicer/wiki/Calibration#Advanced-Calibration))
## 2 高速印刷パラメータの作成
安定して動作する範囲内で高速印刷用のパラメータを作成する。0.3mmピッチで移動速度は600mm/s 20000mm/s^2、印刷速度などは**1**を参考に。orcaslicerのキャリブレーションメニューには各種パラメータのチューニング用データがあるのでそれも利用してください。
## 3 綺麗な印刷パラメータの作成
高速印刷用のパラメータをもとに速度を落とし、時間よりも品質を重視して速度のデチューンを行う。速度の他にも印刷品質に影響するパラメータはあるためそちらも検証する。このパラメータはどうしても綺麗に印刷したい時のみ利用するイメージです。
## 4綺麗な印刷パラメータ用のサポート追加
**3**のパラメータを元にサポート用のパラメータにしていく。サポート用のベンチモデルも[printables](https://www.printables.com/model/260191-support-bench-support-test)などにあるのでそれを利用する。複数のモデルでチェックすることを推奨します。
## 5高速印刷パラメータ用のサポート追加
**4**と同じ

**Comment by nkm071** [comment]
# 印刷結果 240402_1801

湿度：47%
温度：19.9
天気：曇り＊１

## 印刷目的
デフォルトのパラメータで印刷物がどのような状態になるかを確認すること
3D プリンタの使い方を思い出すこと

## 印刷条件
パラメータに関しては特に変更していない．
フィラメント： kexcelled 黒

## 印刷結果
印刷時間：1h38m
後ほど評価を行う.
![image](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/91714744/1164fc8f-b5d3-4e1e-a119-92c52e30b9d1)

![image](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/91714744/325449b0-95ae-49e3-8195-add6fbcd22ee)

## 備考
・基本的に開始時の湿度と温度を記載するが今回に限っては印刷終了時の温度と湿度を記録した．
・天気は[このサイト](https://weather.yahoo.co.jp/weather/12/4510/12204.html)を参考にした．

**Comment by nkm071** [comment]
# 印刷結果 240403_1949

湿度：53%
温度：20.3
天気：雨＊１

## 印刷目的
[高速印刷パラメータ](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/issues/1#issuecomment-2028835841)の作成を行うために積層ピッチ，移動速度と加速度に変更を加えて，印刷時間がどれほど短くなるかを記録する．

## 印刷条件
変更したパラメータに関して，以下のjsonファイルに示す．
[default_param_first_fast_ver1.json](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/files/14851685/default_param_first_fast_ver1.json)
フィラメント： kexcelled 黒

## 印刷結果
印刷時間：1h18m
![IMG_0190](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/91714744/33bbcfab-912e-4f49-9b76-3110ac9460b2)
![IMG_0191](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/91714744/f1c6c992-a9d5-4834-9a41-c08c033e0c9b)

## 感想
デフォルトのパラメータを用いた印刷より，きれいに造形物ができたと感じる．

## 備考
・印刷開始時の湿度と温度を記録した．
＊１天気は[このサイト](https://weather.yahoo.co.jp/weather/12/4510/12204.html)を参考にした．

**Comment by nkm071** [comment]
# 今後の方針
- vfaなどから破綻しない程度に最速を目指す．
1. マシンスペック最大を目指す．
2. 積層高さは0.3[mm]とする．

加えて，今後の3Dプリンタを扱う人のために過程や議論を可能な限り全て情報を記載する．

**Comment by nkm071** [comment]
@MibuchiYuta VFAのモデルはどのように出力すればよいでしょうか．基本的には以下に添付するキャリブレーションのボタンとその種類により，出力されるモデルが変更されると思います．VFAに関して，どのように出力すればよいか教えていただけると助かります．
![image](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/91714744/9c86cb60-f24e-470c-89dc-db429233cd72)

**Comment by nkm071** [comment]
[この件](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/issues/1#issuecomment-2036179743)に関して，VFAについてはマシンスペックの最大値でよいことが確認できているため，そのようにする．

**Comment by nkm071** [comment]
# 印刷結果 240404_1336

湿度：56%
温度：18.9
天気：曇り＊１

## 印刷目的
[高速印刷パラメータ](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/issues/1#issuecomment-2028835841)の作成を行うために壁面，速度，加速度に変更を加えて，印刷時間がどれほど短くなるかを記録する．

## 印刷条件
変更したパラメータに関して，以下のjsonファイルに示す．
[default_param_first_fast_ver2.json](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/files/14861808/default_param_first_fast_ver2.json)
フィラメント： kexcelled 黒

## 印刷結果
印刷時間：1h7m
![IMG_0196](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/91714744/0849b143-612f-4ded-8fce-72de43e6cbf7)
![IMG_0197](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/91714744/476f0178-c266-4dde-9ebf-84fadc0f61a4)

## 感想
[この試行](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/issues/1#issuecomment-2033982843)と比較すると印刷のきれいさは落ちていると感じる．

## 備考
・印刷開始時の湿度と温度を記録した．
＊１天気は[このサイト](https://weather.yahoo.co.jp/weather/12/4510/12204.html)を参考にした．

**Comment by nkm071** [comment]
**今後の方針**
モデルを変更し，3D Benchyを使用する．3D benchyを使用して，パラメータが煮詰まったらkickstarter-autodesk-3dを使用する．

**Comment by kyo0221** [comment]
# 印刷結果_240404_2112

湿度 : 60%
温度 : 15.6℃
天気 : くもり

## 印刷目的
[高速印刷パラメータ](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/issues/1#issuecomment-2028835841)の作成を行うために壁面，速度，加速度に変更を加えて，印刷時間がどれほど短くなるかを記録する．

## 印刷条件
変更したパラメータに関して，以下のjsonファイルに示す．
[3DBenchy_RTA#1 @Creality K1Max (0.4 nozzle).json](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/files/14895995/3DBenchy_RTA.1.%40Creality.K1Max.0.4.nozzle.json)
フィラメント： kexcelled 黒

## 印刷結果
印刷時間：15分14秒
![IMG_6664](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/115678052/44cf6d74-1878-4be1-8466-8833789650ba)
![IMG_6665](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/115678052/a609f36b-0dbf-420a-9a16-42c3fb2c13fc)

## 感想
原型は保っているが1層目に隙間ができているように感じた.

## 備考
・印刷開始時の湿度と温度を記録した．
＊１天気は[このサイト](https://weather.yahoo.co.jp/weather/12/4510/12204.html)を参考にした．

**Comment by nkm071** [comment]
[こちら](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/issues/1#issuecomment-2028835841)の設定ファイルの詰め方について1 マシンスペックの確認から行う．理由は，私自身の理解を深めることとK1 maxのハードウェアの限界を調査するためである．

**作業内容**
- VFA
- Max flowrate
上記について所定のパラメータでキャリブレーションを行う．

**Comment by nkm071** [comment]
VFAについて以下のパラメータで印刷を行う．
Start speed:50mm/s
End speed:650m/s
step:25m/s

![image](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/91714744/6c9f6970-2cd0-48d5-9858-3ce959bf2f54)

**Comment by nkm071** [comment]
Max flowrateについて以下のパラメータで印刷を行う．
Start volumetric speed:5 mm^3/s
End volumetric speed:20 mm^3/s
step:0.5 mm^3/s

![image](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/91714744/236e41f6-9c99-4efc-a3c3-f47d7615482d)

**Comment by nkm071** [comment]
VFAのテストについて記述する．[このコメント](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/issues/1#issuecomment-2046798271)で記載したパラメータで印刷を行った．また，VFAに関しては公式のwikiに言及がないため，[こちらのサイト](https://www.obico.io/blog/orcaslicer-3d-printer-calibration/)のVFAの項を参考にした．

# 印刷結果 240411

湿度：47%
温度：21.5

## 印刷目的
既定のパラメータで印刷したときにどのような印刷結果になるかを記録する．

## 印刷条件
[使用したプロジェクト](https://drive.google.com/file/d/1VMO3XXNdCJxJnmfaSmSfabAvlK0d0MMU/view?usp=drive_link)は上記のリンクにあるがOrcaSlicerの所定のパラメータで印刷を行っているため，意図的に変更したものは以下のパラメータである．
```
Start speed:50mm/s
End speed:650m/s
step:25m/s
```
フィラメント： kexcelled 黒

## 印刷結果
[参考サイト](https://www.obico.io/blog/orcaslicer-3d-printer-calibration/#vertical-fine-artifacts-vfa)においては「垂直壁に細かいアーティファクトや不一致がないか調べる」との指摘がある．そのため，本項においてはそれを基に記述した．

![IMG_0267](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/91714744/da001af7-b947-4260-8ad2-e7461a99bae8)
上記写真において確認ができる凹凸は，325m/sの範囲から確認ができている．425m/sからは凹凸の頻度が高いことが確認できる．
![IMG_0269](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/91714744/cd7fdd5c-8b84-41d4-98f7-2b225500e221)
上記写真において，不一致が見られる範囲は250m/s以上の範囲である．
![IMG_0270](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/91714744/8900920e-15a3-4c26-bd65-3368850c9c73)
上記写真において，ベッドに接する部分が剥がれていることが確認できる．

## 考察
結果より，250m/sの範囲以上ではスムーズかつ安定はしていないとみなした．また，デフォルトのパラメータで印刷したものではないのでそれが影響した可能性は否定できない．

**Comment by nkm071** [comment]
# 追記を行う

Max flowrateのテストについて記述する．[このコメント](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/issues/1#issuecomment-2053925688)このコメントで記載したパラメータで印刷を行った．

# 印刷結果 240414

湿度：54%
温度：21.2

## 印刷目的
既定のパラメータで印刷したときにどのような印刷結果になるかを記録する．



## 印刷条件
[使用したプロジェクト](https://drive.google.com/file/d/1HiwHJfZXXHXEyAQggb0tv-twmWi361s9/view?usp=sharing)は上記のリンクにあるがOrcaSlicerの所定のパラメータで印刷を行っているため，意図的に変更したものは以下のパラメータである．
```
Start volumetric speed:5 mm^3/s
End volumetric speed:20 mm^3/s
step:0.5 mm^3/s
```
フィラメント： kexcelled 黒

## 印刷結果
32mmすべてにわたって正常に印刷OKであることを確認，以下の計算式を用いて最大体積速度を計算するがheightをどこからもってくればよいかわからない．
start + (height-measured * step)
5+(height-measured*0.5)

## 考察

**Comment by MibuchiYuta** [comment]
暫定的な印刷パラメータをcomitしました。以下のやり方で作業しました。

1962ce5d37771ab25ebbd5ee8c85221b100aaec2

> 設定ファイルの詰めかたについて検討しました。参考にしてください。
> 
> ## 1 マシンスペックの確認
> 流量と印刷速度の最大を計測し、それを基準にする。 orcaslicerのキャリブレーションメニューから確認できます。(Max Volmetric speedとVFA。VFAはwiki情報なし [詳細](https://github.com/SoftFever/OrcaSlicer/wiki/Calibration#Advanced-Calibration))
> 
> ## 2 高速印刷パラメータの作成
> 安定して動作する範囲内で高速印刷用のパラメータを作成する。0.3mmピッチで移動速度は600mm/s 20000mm/s^2、印刷速度などは**1**を参考に。orcaslicerのキャリブレーションメニューには各種パラメータのチューニング用データがあるのでそれも利用してください。
> 
> ## 3 綺麗な印刷パラメータの作成
> 高速印刷用のパラメータをもとに速度を落とし、時間よりも品質を重視して速度のデチューンを行う。速度の他にも印刷品質に影響するパラメータはあるためそちらも検証する。このパラメータはどうしても綺麗に印刷したい時のみ利用するイメージです。
> 
> ## 4綺麗な印刷パラメータ用のサポート追加
> **3**のパラメータを元にサポート用のパラメータにしていく。サポート用のベンチモデルも[printables](https://www.printables.com/model/260191-support-bench-support-test)などにあるのでそれを利用する。複数のモデルでチェックすることを推奨します。
> 
> ## 5高速印刷パラメータ用のサポート追加
> **4**と同じ

**Comment by MibuchiYuta** [comment]
また、このコミットでは壁の厚みを増やしたパラメータも追加してあります。

**Comment by MibuchiYuta** [comment]
#16 で評価を行い、問題があれば reopenします。
