### ISSUE TITLE
ベッドメッシュの傾きについて

### ISSUE THREAD

**Issue by ryotaema** [open-rdc/Creality-K1-Slicer-Profiles#15]
ベッドメッシュの傾きがありました。

プリンタの裏のＺ軸ベルトを調整し、以下の画像のように傾きを0.54にまで調整しました。
![ベッドメッシュの傾きについて1](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/147678932/17280d82-f1cc-45a6-b2d2-3c7aebc9ffb3)

**Comment by MibuchiYuta** [comment]
奥だけが下がっているので、プリンター下部のベルトを調整することで解決できると思います。

**Comment by kyo0221** [comment]
ある程度調整が進んだらsimを使って最終調整しましょう.

**Comment by ShoYoshida1** [comment]
simを用いてベッドの傾きを微調整し、端と端の傾きを0.1mm程度まで縮めました。先日に完了したものです。アップ忘れ申し訳ありません
![image](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/148370710/39021e4c-5d95-4f4e-b7be-2c2d5a649c3a)

**Comment by MibuchiYuta** [comment]
@ShoYoshida1 解決しているのであればcloseしてください

**Comment by ShoYoshida1** [comment]
解決しましたのでissueを閉じます。
