### ISSUE TITLE
CoreXYの異音

### ISSUE THREAD

**Issue by nkm071** [open-rdc/Creality-K1-Slicer-Profiles#19]
カラカラという異音がする．

**Comment by nkm071** [comment]
https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/91714744/954c4e2e-e529-4564-8e2e-1a73e89ba1b6

**Comment by nkm071** [comment]
印刷は順調であるため，問題でない可能性もある．

**Comment by nkm071** [comment]
印刷はうまくいっているように見える

![image](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/91714744/5e093826-534a-4b9f-a8a6-5e2a46e11c0e)
![image](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/91714744/44090bdf-1025-41ed-b320-1b6a9d299697)

**Comment by nkm071** [comment]
@MibuchiYuta @kyo0221 こちらのissueに関して問題なければ閉じたいのですがよろしいですか？

**Comment by MibuchiYuta** [comment]
音が鳴る理由の追求だけお願いします。その内容で後回しにするか判断しましょう。

**Comment by nkm071** [comment]
@MibuchiYuta 調査が遅れました申し訳ないです．

## 調査結果
添付の動画より，xとy軸方向に対してエクストルーダが移動しているときに異音がすることが判明した．具体的にどの部品から異音がするかについては添付した写真の赤丸の部品であると結論付ける．異音がなる理由に関しては，プリンタ自体の分解をしたわけではないので推測になるが赤丸の部品の組付けがよくないからという理由が考えられる．

https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/91714744/c3ff15d0-9864-4a22-9ad2-9bffa449a99d

![IMG_0517](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/assets/91714744/09922fca-ff1c-4742-93f3-d827a7b42e24)

**Comment by MibuchiYuta** [comment]
稼働しているものは無給油ブッシュが使われているようです。ロッドも含めてメンテナンス方法があるはずです。

**Comment by MibuchiYuta** [comment]
メンテナンス方法がわかれば
 #3 で議論したいですね。

あとこちらのissueの題名ですがエクストルーダーとしてしまうとフィラメントの押し出し機構に問題があるように思えてしまうので、ヘッドの移動音とかCoreXYの異音とかにした方がいいと思います．

**Comment by nkm071** [comment]
ありがとうございます。issueの名前を変更しました。

- [こちらのissueと同じと思われる問題1](https://www.reddit.com/r/Creality/comments/1512tdp/my_creality_k1_printer_is_making_a_clicking_noise/)
- [こちらのissueと同じと思われる問題2](https://www.reddit.com/r/crealityk1/comments/18akryb/clicking_on_belts_i_think/)
ある程度調査しましたが同じ問題にぶつかっている人はいました。文章を用いた対策は示されていますが動画を用いたメンテナンス方法を提示してくれている人はいませんでした。

**Comment by MibuchiYuta** [comment]
今後どうしますか?

**Comment by nkm071** [comment]
1ヶ月こちらの問題に対する対応が取られていないにも関わらず致命的な問題は引き起こされていないので本issueはクローズしても問題ないと考えています。しかし、ベルト等のメンテナンスに繋がる内容ではあると思いますのでそちらで言及したいと考えています。


@MibuchiYuta 上記の対応でいかがでしょうか。

**Comment by MibuchiYuta** [comment]
わかりました
