### ISSUE TITLE
環境構築手順をwikiにまとめる

### ISSUE THREAD

**Issue by MibuchiYuta** [open-rdc/Creality-K1-Slicer-Profiles#2]
以下の項目を画像付きでwikiに書く

- [x] スライサーのインストール
- [x] 設定ファイルのロード
- [x] Inventorでのstlファイル出力
- [x] スライス
- [x] プリンターの準備・開始・後片付け

**Comment by MibuchiYuta** [comment]
@Ryusei-Baba 
WindowsとUbuntuでのインストール方法に関してwikiの作成をお願いします。

@kyo0221 
スライス方法に関してwikiの作成をお願いします

どちらも4/5から校閲したいのですがどうでしょう?

**Comment by MibuchiYuta** [comment]
@MibuchiYuta 
Inventorでのstlファイル出力とプリンターの準備・開始・後片付けのwiki作成、homeの整備を行います。

**Comment by MibuchiYuta** [comment]
## markdown記法について

[チートシート](https://github.com/MibuchiYuta/git_memo/blob/master/github/markdown.md)を作成したので参考にどうぞ

**Comment by nkm071** [comment]
@MibuchiYuta  質問です．下記のwikiページについて何を書けばよいか議論をしたいです．質問の意図は他のwikiやissueと役割がかぶるのを防ぎたいです．

[wikiページ](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/wiki/%E3%83%97%E3%83%AA%E3%83%B3%E3%82%BF%E3%83%BC%E3%81%AE%E9%96%8B%E5%A7%8B,-%E5%BE%8C%E7%89%87%E4%BB%98%E3%81%91%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)

**Comment by MibuchiYuta** [comment]
印刷前はただgcodeを送る訳ではないはずです。ベッドの用意や動かす前の確認事項、印刷後の取り外し方や後片付けを記載してください

**Comment by nkm071** [comment]
承知しました．ありがとうございます．それらに関して記載します．

**Comment by MibuchiYuta** [comment]
設定ファイルをコミットしたのでこのリポジトリのクローンとファイルの読み込み方法を記載して欲しいです。

**Comment by nkm071** [comment]
@MibuchiYuta [リポジトリのクローンと設定ファイルのロード](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/wiki/%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AE%E3%82%AF%E3%83%AD%E3%83%BC%E3%83%B3%E3%81%A8%E8%A8%AD%E5%AE%9A%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E3%83%AD%E3%83%BC%E3%83%89)をwikiに記載しました。wsl2に関して説明なく使用していますがロボットシステム学で使用した経験があると思うので多少ターミナルを操作できると仮定しています。コメントあればよろしくお願いします。

**Comment by nkm071** [comment]
@MibuchiYuta 
こちらのissueに関して[プリンタの開始, 後片付けについて](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/wiki/%E3%83%97%E3%83%AA%E3%83%B3%E3%82%BF%E3%81%AE%E9%96%8B%E5%A7%8B,-%E5%BE%8C%E7%89%87%E4%BB%98%E3%81%91%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)と[リポジトリのクローンと設定ファイルのロード](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/wiki/%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AE%E3%82%AF%E3%83%AD%E3%83%BC%E3%83%B3%E3%81%A8%E8%A8%AD%E5%AE%9A%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E3%83%AD%E3%83%BC%E3%83%89)が終了していると思います。承認さえしていただければissueを閉じたいと思うのでよろしくお願いします。

**Comment by MibuchiYuta** [comment]
Homeページの編集を私がしたらcloseします

**Comment by MibuchiYuta** [comment]
書きましたのでcloseします
https://github.com/open-rdc/Creality-K1-Slicer-Profiles/wiki
