### ISSUE TITLE
ノズル詰まりについて

### ISSUE THREAD

**Issue by KOYAMA-Yuya** [open-rdc/Creality-K1-Slicer-Profiles#21]
印刷実行時にフィラメントが出てこない問題

**Comment by MibuchiYuta** [comment]
行った作業と、その際の挙動をできるだけ細かく記載してください。大抵は必要な作業が抜けていたり、小さなミスで起きてしまう問題です。

**Comment by MibuchiYuta** [comment]
#23 に関連する問題かもしれません

**Comment by KOYAMA-Yuya** [comment]
#23 と同様の問題であると考えます。
そのためこちらをcloseします
