### ISSUE TITLE
エクストルーダーからの異音

### ISSUE THREAD

**Issue by KOYAMA-Yuya** [open-rdc/Creality-K1-Slicer-Profiles#23]
カタカタという音とともにフィラメントが出てこない問題。
インフィード、解きほぐすともにフィラメントが出てこない

**Comment by MibuchiYuta** [comment]
温度設定が合っているかの確認をしてください。

**Comment by KOYAMA-Yuya** [comment]
設定項目に関しては自分で変更していないため温度設定は合っていると考えています。
今回のフィラメントの送り問題はフィラメントに接触するホブが片持ちで固定されている問題が原因の一つであると考えており、
#10 と同様との判断をし、このissueはcloseします
