### ISSUE TITLE
フィラメントのユーザプリセットが反映されない

### ISSUE THREAD

**Issue by nkm071** [open-rdc/Creality-K1-Slicer-Profiles#24]
[最新のコミット](https://github.com/open-rdc/Creality-K1-Slicer-Profiles/commit/63ca7e49ddc613bf15c79b360bae001682d3bbe3)においてABSのパラメータファイルが作成された。そのファイルをロードしようとしたところ反映されない。反映する様子を動画に示す。

[反映する様子](https://youtu.be/g4ssq9BvuTo)

**Comment by kyo0221** [comment]
私の場合は同じようなロード方法でパラメータファイルが反映されていました.

**Comment by MibuchiYuta** [comment]
OrcaSlicer V2.1.1にてUbuntu,Macで読み込めました

**Comment by MibuchiYuta** [comment]
@hellocit 
中村くんの固有の問題っぽいのでアプリケーションと関連ファイルを一度削除して再インストールする方がいいかもしれません。

**Comment by nkm071** [comment]
@MibuchiYuta 私の環境固有の問題のようですので本issueを閉じます。ありがとうございます。

**Comment by MibuchiYuta** [comment]
ちなみに解決しましたか？

**Comment by nkm071** [comment]
解決していないです。

**Comment by nkm071** [comment]
OS：Windows 11
OrcaSlicerのバージョン：OrcaSlicer V2.1.1

上記で読み込みをしたところ正常に読み込みができました．

差分としては，Windowsのアンインストーラーを用いて削除してから再インストールを行いました．

**Comment by nkm071** [comment]
問題が解決されたので本issueを閉じます．
