### ISSUE TITLE
ノズルが加熱できない問題

### ISSUE THREAD

**Issue by kyo0221** [open-rdc/Creality-K1-Slicer-Profiles#29]
フィラメントが詰まってしまう問題が発生し, ノズル部分にフィラメントが詰まっていると考えて加熱しようとしたが, エラーが表示されて加熱できない問題が発生した.
![IMG_7407](https://github.com/user-attachments/assets/347bbdf1-bca9-411a-ae76-93d4b10dc86b)

**Comment by kyo0221** [comment]
ノズルの配線がちぎれていることを確認した.

![IMG_3958](https://github.com/user-attachments/assets/443a8cfb-89cd-4d55-affb-772f5eccd7bc)

**Comment by kyo0221** [comment]
修理ができないと判断して, 再購入することにしました.

購入品
https://amzn.asia/d/6HCT4zc

**Comment by kyo0221** [comment]
問題の経緯

・3Dプリンターのパラメータチューニングのため, 最大流量の調整をするベンチマークを印刷している途中でフィラメントが出てこなくなっていた

・フィラメントを外し, エクストルーダー部分に汚れ等が溜まっていないか確認した

・汚れ等は認められなかったため, ノズル部分で詰まっていることを疑い, フィラメントがノズル部分に定着していたため加熱しようとした.

・上記のノズルが加熱できない問題が発生した

**Comment by ryotaema** [comment]
購入したノズルに付け替えたところ加熱できるようになりました。
詰まりも加熱したところ解消されていました。
パラメータチューニングに移行します。
